oreo/urls.py
from django.urls import path,include
from . import views

app_name = 'oreo'
urlpatterns =[

    path('', views.index, name='index'),
    path('add_images', views.add_images, name='add_images'),
]

pic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oreo.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oreo/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Images(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    year = models.CharField(max_length=40)
    cover = models.ImageField()

    def __str__(self):
        return self.name

oreo/forms.py
from django import forms
from .models import Images
from django.contrib.auth.models import User


class ImageForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ['name', 'cover', 'year']

oreo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Images
from .forms import ImageForm


# Create your views here.
def index(request):
    images = Images.objects.filter(user=request.user)
    context = {'images': images}
    return render(request, 'oreo/index.html', context)


def add_images(request):
    form = ImageForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        images = form.save(commit=False)
        images.cover = request.FILES['cover']
        images.user = request.user
        images.save()
        return render(request, 'oreo/details.html', {'images': images})
    return render(request, 'oreo/add_images.html', {'form': form})

oreo/templates/oreo/add_album.html
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="panel panel-default" style="">
                    <div class="panel-body"  style="background: navy">
                        <h4 class="text-primary">Add Album</h4>
                        <hr>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit">
                                Submit
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        <div class="col-sm-4"></div>
    </div>
</div>

oreo/templates/oreo/add_images.html
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="panel panel-default" style="">
                    <div class="panel-body"  style="background: navy">
                        <h4 class="text-primary">Add Images</h4>
                        <hr>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit">
                                Submit
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        <div class="col-sm-4"></div>
    </div>
</div>

oreo/templates/oreo/index.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

<div class="container">

      <h3 class="text-primary text-center" style="font-family: 'Arial Black';  color: navy; ">PHOTOS</h3>
        <div class="col-sm-3">
            <ul class="nav nav-pills">
                  <li><a href="{% url 'oreo:add_images' %}">Add Images</a></li>
            </ul>
          </div>
    {% for image in images %}
       <div class="col-sm-3">
       <div class="panel panel-default  my-4" style="background: paleturquoise; ">
           <a href="">
                <img src="{{ image.cover.url }}" class="img img-thumbnail" alt="" style="height: 250px; width: 250px">
           </a>
           <div class="caption" style="margin: 2px">

               <h5>{{ image.name}}</h5>
               <h6>{{ image.year }}</h6>
               <a href="" class="btn btn-primary btn-sm">
                   <i class="fas fa-edit"></i>
               </a>
                <a href="" class="btn btn-info btn-sm">
                   <i class="fas fa-heart"></i>
               </a>
                <a href="" class="btn btn-danger btn-sm" style="float: right" onclick='return confirm("are you sure you want to delete")'>
                   <i class="fas fa-trash"></i>

               </a>


           </div>
       </div>

       </div>
    {% endfor %}
</div>